version: 2.1
jobs:
  pgbench:
    docker:
      - image: buildpack-deps:buster
    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:5b:db:88:e2:e4:00:87:bc:55:c2:11:52:67:d9:0d"
            - "fa:b8:cf:a7:cd:0f:3d:19:3f:85:52:48:e6:e7:a3:39"
      - run:
          command: |
            cd ./azure
            ./add-sshkey.sh
            ./citus-bot.sh citusbot_pgbench_test_resource_group
          name: install dependencies and run pgbench tests
          no_output_timeout: 10m  
          
  scale:
    docker:
      - image: buildpack-deps:buster
    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:5b:db:88:e2:e4:00:87:bc:55:c2:11:52:67:d9:0d"
            - "fa:b8:cf:a7:cd:0f:3d:19:3f:85:52:48:e6:e7:a3:39"
      - run:
          command: |
            cd ./azure
            ./add-sshkey.sh
            ./citus-bot.sh citusbot_scale_test_resource_group
          name: install dependencies and run scale tests
          no_output_timeout: 10m
  
  tpch:
    docker:
      - image: buildpack-deps:buster
    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:5b:db:88:e2:e4:00:87:bc:55:c2:11:52:67:d9:0d"
            - "fa:b8:cf:a7:cd:0f:3d:19:3f:85:52:48:e6:e7:a3:39"
      - run:
          command: |
            cd ./azure
            ./add-sshkey.sh
            ./citus-bot.sh citusbot_tpch_test_resource_group
          name: install dependencies and run tpch tests
          no_output_timeout: 10m   

  delete_resource_group:
    docker:
      - image: buildpack-deps:buster
    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - run:
          command: |
            cd ./azure
            ./delete-resource-group-job.sh
          name: delete the given resource group
          no_output_timeout: 10m             

  valgrind-test:
    docker:
      - image: buildpack-deps:trusty

    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:5b:db:88:e2:e4:00:87:bc:55:c2:11:52:67:d9:0d"
            - "fa:b8:cf:a7:cd:0f:3d:19:3f:85:52:48:e6:e7:a3:39"
      - run:
          command: |
            cd ./azure
            ./add-sshkey.sh
            ./citus-bot.sh citusbot_valgrind_test_resource_group
          name: install dependencies and run valgrind tests
          no_output_timeout: 10m 

  finalize-valgrind-test:
    docker:
      - image: buildpack-deps:trusty

    working_directory: /home/circleci/project  
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:5b:db:88:e2:e4:00:87:bc:55:c2:11:52:67:d9:0d"
            - "fa:b8:cf:a7:cd:0f:3d:19:3f:85:52:48:e6:e7:a3:39"
      - run:
          command: |
            cd ./azure
            ./add-sshkey.sh
            ./finalize-valgrind-test.sh
          name: install dependencies and run valgrind tests
          no_output_timeout: 10m

orbs:
  azure-cli: circleci/azure-cli@1.0.0      

workflows:
  version: 2

  cleanup:
    jobs:
      - delete_resource_group:
          filters:
            branches:
              only:
                - /delete_resource_group\/.*/ # match with delete_resource_group/ prefix

  performance-tests:
    jobs:
      - pgbench:
          filters:
            branches:
              only:
                - /pgbench\/.*/ # match with pgbench/ prefix
                - /all_performance_test\/.*/ # match with all_performance_test/ prefix
      - scale:
          filters:
            branches:
              only: 
                - /scale\/.*/ # match with scale/ prefix
                - /all_performance_test\/.*/ # match with all_performance_test/ prefix
      - tpch:
          filters:
            branches:
              only: 
                - /tpch\/.*/ # match with tpch/ prefix
                - /all_performance_test\/.*/ # match with all_performance_test/ prefix

  # perform weekly valgrind test on azure every monday at 00:00
  weekly-valgrind:
    triggers:
      - schedule:
          # https://crontab.guru/#0_0_*_*_1
          cron: "0 0 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - valgrind-test

  # Since valgrind tests really take a long time to finish, wait for 12 hours.
  # Then push valgrind test results and terminate the machine.
  weekly-valgrind-finalize:
    triggers:
      - schedule:
          # https://crontab.guru/#00_12_*_*_1
          cron: "00 12 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - finalize-valgrind-test

  onpush-valgrind:
    jobs:
      - valgrind-test
  # onpush-finalize-valgrind:
  #   jobs:
  #     - finalize-valgrind-test
