VACUUM ANALYZE nation;
SELECT COUNT(*) FROM nation;
SELECT COUNT(*) FROM nation;
SELECT COUNT(*) FROM nation;

VACUUM ANALYZE region;
SELECT COUNT(*) FROM region;
SELECT COUNT(*) FROM region;
SELECT COUNT(*) FROM region;

VACUUM ANALYZE part;
SELECT COUNT(*) FROM part;
SELECT COUNT(*) FROM part;
SELECT COUNT(*) FROM part;

VACUUM ANALYZE supplier;
SELECT COUNT(*) FROM supplier;
SELECT COUNT(*) FROM supplier;
SELECT COUNT(*) FROM supplier;

VACUUM ANALYZE partsupp;
SELECT COUNT(*) FROM partsupp;
SELECT COUNT(*) FROM partsupp;
SELECT COUNT(*) FROM partsupp;

VACUUM ANALYZE customer;
SELECT COUNT(*) FROM customer;
SELECT COUNT(*) FROM customer;
SELECT COUNT(*) FROM customer;

VACUUM ANALYZE orders;
SELECT COUNT(*) FROM orders;
SELECT COUNT(*) FROM orders;
SELECT COUNT(*) FROM orders;

VACUUM ANALYZE lineitem;
SELECT COUNT(*) FROM lineitem;
SELECT COUNT(*) FROM lineitem;
SELECT COUNT(*) FROM lineitem;
